version: "3"
services:
  nginx:
    image: nginx:1.15.6
    ports:
      - "90:80"
      - "8000:8000"
      - "8002:8002"
      - "8004:8004"
    depends_on:
      - app
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    build: ./docker/php
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: suggestionbox
      MYSQL_USER: globalituser
      MYSQL_PASSWORD: GlobalIT@123
      MYSQL_ROOT_PASSWORD: GlobalIT@123
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
